// <auto-generated />
using System;
using EurovisionHub.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EurovisionHub.Migrations
{
    [DbContext(typeof(EurovisionContext))]
    [Migration("20260330013728_AddPlaceToParticipation")]
    partial class AddPlaceToParticipation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EurovisionHub.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)");

                    b.Property<string>("FlagUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("character varying");

                    b.HasKey("Id")
                        .HasName("Country_pkey");

                    b.ToTable("Country", (string)null);
                });

            modelBuilder.Entity("EurovisionHub.Models.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("HostCountryId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("TypeId")
                        .HasColumnType("integer");

                    b.HasKey("Id")
                        .HasName("Event_pkey");

                    b.HasIndex("HostCountryId");

                    b.HasIndex("TypeId");

                    b.ToTable("Event", (string)null);
                });

            modelBuilder.Entity("EurovisionHub.Models.EventType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("character varying");

                    b.HasKey("Id")
                        .HasName("EventType_pkey");

                    b.ToTable("EventType", (string)null);
                });

            modelBuilder.Entity("EurovisionHub.Models.Participation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<int>("CountryId")
                        .HasColumnType("integer");

                    b.Property<int>("EventId")
                        .HasColumnType("integer");

                    b.Property<int?>("OrderNumber")
                        .HasColumnType("integer");

                    b.Property<int?>("Place")
                        .HasColumnType("integer");

                    b.Property<int>("SongId")
                        .HasColumnType("integer");

                    b.HasKey("Id")
                        .HasName("Participation_pkey");

                    b.HasIndex("CountryId");

                    b.HasIndex("EventId");

                    b.HasIndex("SongId");

                    b.ToTable("Participation", (string)null);
                });

            modelBuilder.Entity("EurovisionHub.Models.Song", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("VideoUrl")
                        .HasColumnType("text");

                    b.HasKey("Id")
                        .HasName("Song_pkey");

                    b.ToTable("Song", (string)null);
                });

            modelBuilder.Entity("EurovisionHub.Models.Vote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<int>("EventId")
                        .HasColumnType("integer");

                    b.Property<int>("FromCountryId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsJury")
                        .HasColumnType("boolean");

                    b.Property<int>("Points")
                        .HasColumnType("integer");

                    b.Property<int>("ToParticipationId")
                        .HasColumnType("integer");

                    b.HasKey("Id")
                        .HasName("Vote_pkey");

                    b.HasIndex("EventId");

                    b.HasIndex("FromCountryId");

                    b.HasIndex("ToParticipationId");

                    b.ToTable("Vote", (string)null);
                });

            modelBuilder.Entity("EurovisionHub.Models.Event", b =>
                {
                    b.HasOne("EurovisionHub.Models.Country", "HostCountry")
                        .WithMany("HostedEvents")
                        .HasForeignKey("HostCountryId")
                        .IsRequired()
                        .HasConstraintName("HostCountry_fkey");

                    b.HasOne("EurovisionHub.Models.EventType", "Type")
                        .WithMany("Events")
                        .HasForeignKey("TypeId")
                        .IsRequired()
                        .HasConstraintName("EventType_fkey");

                    b.Navigation("HostCountry");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("EurovisionHub.Models.Participation", b =>
                {
                    b.HasOne("EurovisionHub.Models.Country", "Country")
                        .WithMany("Participations")
                        .HasForeignKey("CountryId")
                        .IsRequired()
                        .HasConstraintName("Country_fkey");

                    b.HasOne("EurovisionHub.Models.Event", "Event")
                        .WithMany("Participations")
                        .HasForeignKey("EventId")
                        .IsRequired()
                        .HasConstraintName("Event_fkey");

                    b.HasOne("EurovisionHub.Models.Song", "Song")
                        .WithMany("Participations")
                        .HasForeignKey("SongId")
                        .IsRequired()
                        .HasConstraintName("Song_fkey");

                    b.Navigation("Country");

                    b.Navigation("Event");

                    b.Navigation("Song");
                });

            modelBuilder.Entity("EurovisionHub.Models.Vote", b =>
                {
                    b.HasOne("EurovisionHub.Models.Event", "Event")
                        .WithMany("Votes")
                        .HasForeignKey("EventId")
                        .IsRequired()
                        .HasConstraintName("Event_fkey");

                    b.HasOne("EurovisionHub.Models.Country", "FromCountry")
                        .WithMany("Votes")
                        .HasForeignKey("FromCountryId")
                        .IsRequired()
                        .HasConstraintName("FromCountry_fkey");

                    b.HasOne("EurovisionHub.Models.Participation", "ToParticipation")
                        .WithMany("Votes")
                        .HasForeignKey("ToParticipationId")
                        .IsRequired()
                        .HasConstraintName("ToParticipation_fkey");

                    b.Navigation("Event");

                    b.Navigation("FromCountry");

                    b.Navigation("ToParticipation");
                });

            modelBuilder.Entity("EurovisionHub.Models.Country", b =>
                {
                    b.Navigation("HostedEvents");

                    b.Navigation("Participations");

                    b.Navigation("Votes");
                });

            modelBuilder.Entity("EurovisionHub.Models.Event", b =>
                {
                    b.Navigation("Participations");

                    b.Navigation("Votes");
                });

            modelBuilder.Entity("EurovisionHub.Models.EventType", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("EurovisionHub.Models.Participation", b =>
                {
                    b.Navigation("Votes");
                });

            modelBuilder.Entity("EurovisionHub.Models.Song", b =>
                {
                    b.Navigation("Participations");
                });
#pragma warning restore 612, 618
        }
    }
}
